# Generated by Django 4.2.4 on 2023-09-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_task_item_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='task',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_plan',
        ),
        migrations.CreateModel(
            name='ItemTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plan', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
            options={
                'unique_together': {('task', 'item')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tasks',
            field=models.ManyToManyField(related_name='items', through='api.ItemTask', to='api.task'),
        ),
    ]
